apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-deployment-rolling
spec:
  replicas : 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
  selector :
    matchLabels :
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      containers:
        - name: metadata-service
          image: sunitparekh/metadata:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "3.2"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
