apiVersion: v1
kind: Service
metadata:
  name: metadata-svc-nodeport
spec:
  type: NodePort
  selector:
    app: metadata-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30005